name: CI

on:
  push:
    branches:
      - hw3
  pull_request:
    branches:
      - hw3

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        options: >-
          --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock
        env:
          SERVICES: dynamodb,s3
          DEBUG: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set executable permissions for test.sh
        run: chmod +x ./test.sh

      - name: Run tests
        run: ./test.sh
